repos:
  - repo: local
    hooks:
      - id: Server lint
        name: Clippy
        entry: bash -c 'cd server && cargo clippy --all-targets -- -D warnings'
        language: system
        files: ^server/
        pass_filenames: false

      - id: Server formatter
        name: Cargo fmt
        entry: bash -c 'cd server && cargo fmt -- --check'
        language: system
        files: ^server/
        pass_filenames: false